CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL IDENTITY, 
    [UserName] NVARCHAR(MAX) NOT NULL, 
    [Password] NVARCHAR(MAX) NOT NULL,
	CONSTRAINT [PK_Users_Id] PRIMARY KEY CLUSTERED ([Id] ASC),
)
